### ISSUE TITLE
Expected Running Time For Evaluation

### ISSUE THREAD

**Issue by xgeric** [IBM/RuDaS#3]
Hi,

Thank you for the inspiring work! I am trying to run your example experiment (only on exp1, AMIE+, complete). It has taken over 48 hours to run on 5 datasets... I am wondering what is the expected running time for evaluation over all the datasets and systems?

Thank you!

**Comment by corneliocristina** [comment]
Hi, the following metrics require the grounding of the induced logic program: herbrand_distance, **herbrand_accuracy, herbrand_score, accuracy, precision, recall, f1score**. For this reason, if the induced rules are not of good quality it can take a while to finish to run.

We just added an evaluation metric that doesn't require to ground the logic programs: **rules_score**. This one is very fast to compute. You can find more details in the new version of the paper on arXiv (section 5.3) https://arxiv.org/abs/1909.07095 .
